### ISSUE TITLE
Do it support vector tiles

### ISSUE THREAD

**Issue by anuragvohraec** [RobertSasak/mbtiles-serve#1]
hi Robert,

I tried this with raster based mbtiles and its working.
But for vector mbtiles, it seems to be not working. Just getting empty tiles.

Do it supports vector tiles or only raster tiles.

**Comment by RobertSasak** [comment]
This library serves whatever it in the mbtiles. It does not matter whether it is raster or vector tile. Can you please provide some simple test case?

**Comment by anuragvohraec** [comment]
I extracted mbtiles for my city, from : https://extract.bbbike.org/,
And then ran `mbtiles-serve ashta.mbtiles`, but the map loads as blank:
![image](https://user-images.githubusercontent.com/53807480/179394756-1a0d5bab-d17e-4509-82ce-f33a4e026742.png)

Adding the mbtiles file for your reference:
[ashta.mbtiles.zip](https://github.com/RobertSasak/mbtiles-serve/files/9127446/ashta.mbtiles.zip)
I have added just **.zip* to upload it here, just rename it by removing **.zip** from its name.

I have tried it with raster based mbtiles files (created from tilemill) and it works fine.
Do you have a link to vector based tiles, which works with this.

Thank you for your help.

**Comment by RobertSasak** [comment]
MBtiles is a databases of tiles. In your case it stores tiles in MVT format. Those tiles are served to the browser. However Leafletjs nor browser does not know how to show MVT file. 

You have two options:
You can try to add https://github.com/SpatialServer/Leaflet.MapboxVectorTile plugin into leaflet which provides support for MVT. Simply edit assets/index.html
Or you can try another MapboxGL instead of LeafletJS. https://docs.mapbox.com/mapbox-gl-js/example/third-party/

Let me know it you manage to make it work. It would be great to add it to this library.

**Comment by anuragvohraec** [comment]
> Let me know it you manage to make it work.

I have left for tha day, I will try your suggestions tomorrow and let you know.

**Comment by anuragvohraec** [comment]
Hi Robert,

Your example code uses leaflet >1.0, and hence tried using other solutions, as suggested here without success.
https://leafletjs.com/plugins.html#vector-tiles

**Comment by RobertSasak** [comment]
Image tiles are easy to show on map. However Vector tiles requires styles as well which are not part of the mbtiles. This library can still serve vector tiles but you need to create your own html client.
